# Standards: 0.11
---

- include: "level-2/4.1.8.yml"
  when: "'4.1.8' not in cis_level_2_exclusions"
- include: "level-2/4.1.9.yml"
  when: "'4.1.9' not in cis_level_2_exclusions"
- include: "level-2/4.1.10.yml"
  when: "'4.1.10' not in cis_level_2_exclusions"
- include: "level-2/4.1.11.yml"
  when: "'4.1.11' not in cis_level_2_exclusions"
- include: "level-2/4.1.13.yml"
  when: "'4.1.13' not in cis_level_2_exclusions"
- include: "level-2/4.1.14.yml"
  when: "'4.1.14' not in cis_level_2_exclusions"
- include: "level-2/4.1.15.yml"
  when: "'4.1.15' not in cis_level_2_exclusions"
- include: "level-2/4.1.16.yml"
  when: "'4.1.16' not in cis_level_2_exclusions"
- include: "level-2/4.1.17.yml"
  when: "'4.1.17' not in cis_level_2_exclusions"
- include: "level-2/4.1.18.yml"
  when: "'4.1.18' not in cis_level_2_exclusions"   
- include: "level-2/6.1.1.yml"
  when: "'6.1.1' not in cis_level_2_exclusions"
- include: "level-2/4.1.1.2.yml"
  when: "'4.1.1.2' not in cis_level_2_exclusions" 
- include: "level-2/4.1.1.3.yml"
  when: "'4.1.1.3' not in cis_level_2_exclusions"
- include: "level-2/4.1.2.yml"
  when: "'4.1.2' not in cis_level_2_exclusions"
- include: "level-2/4.1.4.yml"
  when: "'4.1.4' not in cis_level_2_exclusions" 
- include: "level-2/4.1.5.yml"
  when: "'4.1.5' not in cis_level_2_exclusions"
- include: "level-2/4.1.6.yml"
  when: "'4.1.6' not in cis_level_2_exclusions"
- include: "level-2/4.1.7.yml"
  when: "'4.1.7' not in cis_level_2_exclusions"
       
