# Standards: 0.11
---

# 4.1.11 Ensure unsuccessful unauthorized file access attempts are collected (Scored)

- name: 4.1.11 Ensure unsuccessful unauthorized file access attempts are collected (Scored)
  shell: "grep access {{ cis_audit_rules_filename }}"
  register: access
  changed_when: False
  ignore_errors: true
  tags:
    - "4.1.11"
    - level-2
    - section-4
    - scored


- name: 4.1.11 Ensure unsuccessful unauthorized file access attempts are collected(Verify registered output matches)
  lineinfile:
    dest: "{{ cis_audit_rules_filename }}"
    line: "{{ item }}"
  with_items:
    - '# 4.1.11 Ensure unsuccessful unauthorized file access attempts are collected'
    - '-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EACCES -F auid>=500 -F auid!=4294967295 -k access'
    - '-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EACCES -F auid>=500 -F auid!=4294967295 -k access'
    - '-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EPERM -F auid>=500 -F auid!=4294967295 -k access'
    - '-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EPERM -F auid>=500 -F auid!=4294967295 -k access'

  tags:
    - "4.1.11"
    - level-2
    - section-4
    - scored







