# Standards: 0.11
---

# 4.1.15 Ensure changes to system administration scope (sudoers) is collected (Scored)

- name: 4.1.15 Ensure changes to system administration scope (sudoers) is collected (Scored)
  shell: "grep scope {{ cis_audit_rules_filename }}"
  register: scope
  changed_when: False
  ignore_errors: true
  tags:
    - "4.1.15"
    - level-2
    - section-4
    - scored


- name: 4.1.15 Ensure changes to system administration scope (sudoers) is collected(Verify registered output matches)
  lineinfile:
    dest: "{{ cis_audit_rules_filename }}"
    line: "{{ item }}"
  with_items:
    - '# 4.1.15 Ensure changes to system administration scope (sudoers) is collected'
    - '-w /etc/sudoers -p wa -k scope'
    - '-w /etc/sudoers.d -p wa -k scope'
  when:
    ("'-w /etc/sudoers -p wa -k scope' not in scope.stdout") or
    ("'-w /etc/sudoers.d -p wa -k scope' not in scope.stdout")
  tags:
    - "4.1.15"
    - level-2
    - section-4
    - scored
