# Standards: 0.11
---
#4.1.8 Ensure login and logout events are collected(Scored)

- name: 4.1.8 Ensure login and logout events are collected(Scored)
  shell: "grep logins {{ cis_audit_rules_filename }}"
  register: logins
  changed_when: False
  ignore_errors: true
  tags:
    - "4.1.8"
    - level-2
    - section-4
    - scored


- name: 4.1.8 Ensure login and logout events are collected (Verify registered output matches)
  lineinfile:
    dest: "{{ cis_audit_rules_filename }}"
    line: "{{ item }}"
  with_items:
    - '# 4.1.8 Ensure login and logout events are collected'
    - '-w /var/log/lastlog -p wa -k logins'
    - '-w /var/run/faillock/ -p wa -k logins'
  when:
       ("'-w /var/run/faillock/ -p wa -k logins' not in logins.stdout") or
       ("'-w /var/log/lastlog -p wa -k logins' not in logins.stdout")

  tags:
    - "4.1.8"
    - level-2
    - section-4
    - scored
