# Standards: 0.11
---

# 4.1.13 Ensure successful file system mounts are collected (Scored)

- name: 4.1.13 Ensure successful file system mounts are collected (Scored)
  shell: "grep mounts {{ cis_audit_rules_filename }}"
  register: mounts
  changed_when: False
  ignore_errors: true
  tags:
    - "4.1.13"
    - level-1
    - section-4
    - scored


- name: 4.1.13 Ensure successful file system mounts are collected (Scored)(Verify registered output matches)
  lineinfile:
    dest: "{{ cis_audit_rules_filename }}"
    line: "{{ item }}"
  with_items:
    - '# 4.1.13 Ensure successful file system mounts are collected (Scored)'
    - '-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts'
    - '-a always,exit -F arch=b32 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts'
  when:
    ("'-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts' not in mounts.stdout") or
    ("'-a always,exit -F arch=b32 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts' not in mounts.stdout")
  tags:
    - "4.1.13"
    - level-1
    - section-4
    - scored
