# Standards: 0.11
---

#4.1.9 Ensure session initiation information is collected (Scored)

- name: 4.1.9 Ensure session initiation information is collected (Scored)
  shell: "grep session {{ cis_audit_rules_filename }}"
  register: session
  changed_when: False
  ignore_errors: true
  tags:
    - "4.1.9"
    - level-2
    - section-4
    - scored


- name: 4.1.9 Ensure session initiation information is collected(Verify registered output matches)
  lineinfile:
    dest: "{{ cis_audit_rules_filename }}"
    line: "{{ item }}"
  with_items:
    - '# 4.1.9 Ensure login and logout events are collected'
    - '-w /var/run/utmp -p wa -k session'
    - '-w /var/log/wtmp -p wa -k session'
    - '-w /var/log/btmp -p wa -k session'
  when:
    ("'-w /var/run/utmp -p wa -k session' not in session.stdout") or
    ("'-w /var/log/wtmp -p wa -k session' not in session.stdout") or
    ("'-w /var/log/btmp -p wa -k session' not in session.stdout")
  tags:
    - "4.1.9"
    - level-2
    - section-4
    - scored

