# Standards: 0.11
---

# 4.1.5 Ensure events that modify user/group information are collected(Scored)

- name: 4.1.5 Ensure events that modify user/group information are collected(Scored)
  shell: "grep identity {{ cis_audit_rules_filename }}"
  register: identity
  changed_when: False
  ignore_errors: true
  tags:
    - "4.1.5"
    - level-2
    - section-4
    - scored


- name: 4.1.5 Ensure events that modify user/group information are collected(Scored)(Verify registered output matches)
  lineinfile:
    dest: "{{ cis_audit_rules_filename }}"
    line: "{{ item }}"
  with_items:
    - '# 4.1.5 Ensure events that modify date and time information are collected'
    - '-w /etc/group -p wa -k identity'
    - '-w /etc/passwd -p wa -k identity'
    - '-w /etc/gshadow -p wa -k identity'
    - '-w /etc/shadow -p wa -k identity'
    - '-w /etc/security/opasswd -p wa -k identity'
  when:
    ("'-w /etc/group -p wa -k identity' not in identity.stdout") or
    ("'-w /etc/passwd -p wa -k identity' not in identity.stdout") or
    ("'-w /etc/gshadow -p wa -k identity' not in identity.stdout") or
    ("'-w /etc/shadow -p wa -k identity' not in identity.stdout") or
    ("'-w /etc/security/opasswd -p wa -k identity' not in identity.stdout")
  tags:
    - "4.1.5"
    - level-2
    - section-4
    - scored
