# Standards: 0.11
---

# 4.1.18 Ensure the audit configuration is immutable (Scored)

- name: 4.1.18 Ensure the audit configuration is immutable (Scored)
  shell: grep "^\s*[^#]" {{ cis_audit_rules_filename }} | tail -1
  register: immutable
  changed_when: False
  ignore_errors: true
  tags:
    - "4.1.18"
    - level-2
    - section-4
    - scored


- name: 4.1.18 Ensure the audit configuration is immutable(Verify registered output matches)
  lineinfile:
    dest: "{{ cis_audit_rules_filename }}"
    line: "{{ item }}"
  with_items:
    - '# 4.1.18 Ensure the audit configuration is immutable'
    - '-e 2'
  when:
    ("'-e 2' not in immutable.stdout")
  tags:
    - "4.1.18"
    - level-2
    - section-4
    - scored
