# Standards: 0.11
---

# 4.1.1.2 Ensure system is disabled when audit logs are full (Scored)

- name: 4.1.1.2- Check if CIS audit.d configuration file exists
  stat:
    path: "{{ cis_audit_auditd_filename }}"
  register: auditd_4_1_1_2
  tags:
    - level-1
    - section-1
    - "4.1.1.2"
    - scored

- name: 4.1.1.2 Ensure system is disabled when audit logs are full (Scored)
  lineinfile:
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    dest: "{{ cis_audit_auditd_filename }}"
    state: present
  with_items:
    - { regexp: "space_left_action = SYSLOG", line: "space_left_action = email" }
    - { regexp: "admin_space_left_action = SUSPEND", line: "admin_space_left_action = halt" }
  notify: Restart auditd
  when: auditd_4_1_1_2.stat.exists is not defined or not auditd_4_1_1_2.stat.exists
  tags:
    - level-2
    - section-4
    - "4.1.1.2"
    - scored


