# Standards: 0.11
---

# 4.1.14 Ensure file deletion events by users are collected (Scored)

- name: 4.1.14 Ensure file deletion events by users are collected (Scored)
  shell: "grep delete {{ cis_audit_rules_filename }}"
  register: delete
  changed_when: False
  ignore_errors: true
  tags:
    - "4.1.14"
    - level-1
    - section-4
    - scored


- name: 4.1.14 Ensure file deletion events by users are collected(Verify registered output matches)
  lineinfile:
    dest: "{{ cis_audit_rules_filename }}"
    line: "{{ item }}"
  with_items:
    - '# 4.1.14 Ensure file deletion events by users are collected'
    - '-a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -F auid>=500 -F auid!=4294967295 -k delete'
    - '-a always,exit -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -F auid>=500 -F auid!=4294967295 -k delete'
  when:
    ("'-a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -F auid>=500 -F auid!=4294967295 -k delete' not in delete.stdout") or
    ("'-a always,exit -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -F auid>=500 -F auid!=4294967295 -k delete' not in delete.stdout")
  tags:
    - "4.1.14"
    - level-1
    - section-4
    - scored







