# Standards: 0.11
---

# 1.1.11 Ensure separate partition exists for /var/log (Scored)

- name: 1.1.11 Ensure separate partition exists for /var/log (Scored)
  mount:
    name: "{{ item.mountpoint }}"
    state: present
    fstype: "{{item.fstype}}"
    src: "{{item.device}}"
  with_items:
    - { mountpoint: "{{cis_partition_mnt_val_log}}", device: "{{cis_partition_dev_val_log}}", fstype: "{{cis_partition_fs_val_log}}" }
  tags:
      - level-1
      - section-1
      - "1.1.11"
      - scored
