---
# Standards: 0.11

# 1.1.1.1 - Ensure mounting of cramfs filesystems is disabled

- name: 1.1.1.1 - Check if CIS modprobe configuration file exists
  stat:
    path: "{{ cis_modprobe_conf_filename }}"
  register: modprobe_1_1_1_1
  tags:
    - level-1
    - section-1
    - "1.1.1.1"
    - scored

- name: 1.1.1.1 - Ensure mounting of cramfs filesystems is disabled
  copy:
    dest: "{{ cis_modprobe_conf_filename }}"
    content: "install cramfs /bin/true\n"
  when: modprobe_1_1_1_1.stat.exists is not defined or not modprobe_1_1_1_1.stat.exists
  tags:
    - level-1
    - section-1
    - "1.1.1.1"
    - scored

- name: 1.1.1.1 - Ensure mounting of cramfs filesystems is disabled
  lineinfile:
    dest: "{{ cis_modprobe_conf_filename }}"
    regexp: "^install cramfs"
    line: "install cramfs /bin/true"
  when: modprobe_1_1_1_1.stat.exists is defined and modprobe_1_1_1_1.stat.exists
  tags:
    - level-1
    - section-1
    - "1.1.1.1"
    - scored
