# Standards: 0.11
---

# 1.5.4 Ensure prelink is disabled

- name: Check if prelink binary exists
  command: which prelink
  ignore_errors: true
  register: which_1_5_4
  tags:
    - level-1
    - "1.5.4"
    - scored

- name: Restore prelinked binaries
  command: prelink -ua
  when: which_1_5_4.rc is defined and which_1_5_4.rc == 0
  tags:
    - level-1
    - "1.5.4"
    - scored

- name: Ensure prelink is disabled
  yum:
    name: prelink
    state: absent
  tags:
    - level-1
    - "1.5.4"
    - scored
