# Standards: 0.11
---

# 1.6.1.6 Ensure no unconfined daemons exist (Scored)

- name: 1.6.1.6 Ensure no unconfined daemons exist (Scored)
  script: "{{ role_path }}/files/audit_1.6.1.6.sh"
  always_run: yes
  changed_when: False
  register: audit_1_6_1_6
  tags:
    - level-1
    - section-6
    - "1.6.1.6"
    - scored

- name: 1.6.1.6 Ensure no unconfined daemons exist (Scored)
  fail:
    msg: "{{ audit_1_6_1_6.stdout_lines }}"
  when:
    - audit_1_6_1_6.stdout_lines is defined and audit_1_6_1_6.stdout_lines|length > 0
    - fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - "1.6.1.6"
    - scored

- name: 1.6.1.6 Ensure no unconfined daemons exist (Scored)
  debug:
    msg: "*** ACTION REQUIRED *** {{ audit_1_6_1_6.stdout }}"
  when:
    - audit_1_6_1_6.stdout_lines is defined and audit_1_6_1_6.stdout_lines|length > 0
    - not fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - "1.6.1.6"
    - scored
