# Standards: 0.11
---

# 1.7.1.2 Ensure local login warning banner is configured properly

- name: 1.7.1.2 - Ensure local login warning banner is configured properly
  copy:
    content: "{{ cis_local_login_warning_banner }}"
    dest: "/etc/issue"
  tags:
    - level-1
    - 1.7.1.2
    - not-scored
