# Standards: 0.11
---

# 2.2.1.3 Ensure chrony is configured
- name: Set Options -u chrony in /etc/sysconfig/chronyd
  lineinfile:
    path: /etc/sysconfig/chronyd
    regexp: '^OPTIONS=.*$'
    line: 'OPTIONS="-u chrony"'
    state: present
  when: cis_enable_chrony
  tags:
    - level-1
    - "2.2.1.3"
    - scored

- name: Set remote server
  lineinfile:
    path: /etc/chrony.conf
    line: "server {{ cis_chrony_remote_server }}"
    state: present
  when: cis_enable_chrony
  tags:
    - level-1
    - "2.2.1.3"
    - scored
