# Standards: 0.11
---

# 3.2.9 Ensure IPv6 router advertisements are not accepted (Scored)

- name: 3.2.9 - Ensure IPv6 router advertisements are not accepted (Scored)
  sysctl:
    ignoreerrors: yes
    name: "{{ item }}"
    value: "0"
    state: present
  with_items:
    - "net.ipv6.conf.all.accept_ra"
    - "net.ipv6.conf.default.accept_ra"
  tags:
    - level-1
    - section-3
    - "3.2.9"
    - scored

- name: 3.2.9 - Ensure IPv6 router advertisements are rejected by active kernel
  command: "{{ item }}"
  with_items:
    - "sysctl -w net.ipv6.conf.all.accept_ra=0"
    - "sysctl -w net.ipv6.conf.default.accept_ra=0"
    - "sysctl -w net.ipv6.route.flush=1"
  tags:
    - level-1
    - section-3
    - "3.2.9"
    - scored
