# Standards: 0.11
---

# 3.3.3 Ensure /etc/hosts.deny is configured

- name: 3.3.3 - Check if /etc/hosts.deny configuration file exists
  stat:
    path: "/etc/hosts.deny"
  register: hosts_deny_3_4_3
  tags:
    - level-1
    - section-3
    - "3.3.3"
    - scored

- name: 3.3.3 - Ensure /etc/hosts.deny is configured
  copy:
    path: "/etc/hosts.deny"
    content: "ALL: ALL\n"
  when: hosts_deny_3_4_3.stat.exists is not defined or not hosts_deny_3_4_3.stat.exists
  tags:
    - level-1
    - section-3
    - "3.3.3"
    - scored

- name: 3.3.3 - Ensure /etc/hosts.deny is configured
  lineinfile:
    dest: "/etc/hosts.deny"
    regexp: "^ALL:"
    line: "ALL: ALL"
  when: hosts_deny_3_4_3.stat.exists is defined and hosts_deny_3_4_3.stat.exists
  tags:
    - level-1
    - section-3
    - "3.3.3"
    - scored
