# Standards: 0.11
---

# 5.1.5 Ensure permissions on /etc/cron.weekly are configured

- name: 5.1.5 - Ensure permissions on /etc/cron.weekly are configured
  file:
    path: "/etc/cron.weekly"
    owner: root
    group: root
    mode: 0700
  tags:
    - level-1
    - section-5
    - "5.1.5"
    - scored
