# Standards: 0.11
---

# 5.1.3 Ensure permissions on /etc/cron.hourly are configured

- name: 5.1.3 - Ensure permissions on /etc/cron.hourly are configured
  file:
    path: "/etc/cron.hourly"
    owner: root
    group: root
    mode: 0700
  tags:
    - level-1
    - section-5
    - "5.1.3"
    - scored
