# Standards: 0.11
---

# 5.1.7 Ensure permissions on /etc/cron.d are configured

- name: 5.1.7 - Ensure permissions on /etc/cron.d are configured
  file:
    path: "/etc/cron.d"
    owner: root
    group: root
    mode: 0700
    state: directory
  tags:
    - level-1
    - section-5
    - "5.1.7"
    - scored
