# Standards: 0.11
---

# 5.1.4 Ensure permissions on /etc/cron.daily are configured

- name: 5.1.4 - Ensure permissions on /etc/cron.daily are configured
  file:
    path: "/etc/cron.daily"
    owner: root
    group: root
    mode: 0700
  tags:
    - level-1
    - section-5
    - "5.1.4"
    - scored
