---

# 5.1.2 Ensure permissions on /etc/crontab are configured

- name: 5.1.2 - Ensure permissions on /etc/crontab are configured
  file:
    path: "/etc/crontab"
    owner: root
    group: root
    mode: 0600
  tags:
    - level-1
    - "5.1.2"
    - scored
