# Standards: 0.11
---

# 5.2.1 Ensure permissions on /etc/ssh/sshd_config are configured

- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - "5.2.1"
    - scored

- name: 5.2.1 - Ensure permissions on /etc/ssh/sshd_config are configured
  file:
    path: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
  when: sshd_config.stat.exists
  tags:
    - level-1
    - section-5
    - "5.2.1"
    - scored
