# Standards: 0.11
---

# 5.2.12 - Ensure SSH PermitUserEnvironment is disabled

- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - "5.2.12"
    - scored

- name: 5.2.12 - Ensure SSH PermitUserEnvironment is disabled
  lineinfile:
    regexp: "^PermitUserEnvironment\\s+"
    line: "PermitUserEnvironment no"
    dest: "{{ cis_sshd_config_filename }}"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.12"
    - scored
