# Standards: 0.11
---

# 5.2.11 - Ensure SSH PermitEmptyPasswords is disabled

- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - "5.2.11"
    - scored

- name: 5.2.11 - Ensure SSH PermitEmptyPasswords is disabled
  lineinfile:
    regexp: "^PermitEmptyPasswords\\s+"
    line: "PermitEmptyPasswords no"
    dest: "{{ cis_sshd_config_filename }}"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.11"
    - scored
