# Standards: 0.11
---

# 5.2.19 - Ensure SSH warning banner is configured

- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - "5.2.19"
    - scored

- name: 5.2.19 - Ensure SSH warning banner is configured
  lineinfile:
    regexp: "^Banner\\s+"
    line: "Banner {{ cis_sshd_banner }}"
    dest: "{{ cis_sshd_config_filename }}"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.19"
    - scored
