# Standards: 0.11
---

# 5.2.10 Ensure SSH root login is disabled

- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - "5.2.10"
    - scored

- name: 5.2.10 - Ensure SSH root login is disabled
  lineinfile:
    regexp: "^PermitRootLogin\\s+"
    line: "PermitRootLogin no"
    dest: "{{ cis_sshd_config_filename }}"
  when: sshd_config.stat.exists
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.10"
    - scored
