# Standards: 0.11
---

# 5.4.3 Ensure default group for the root account is GID 0

- name: 5.4.3 - Check the GID of the root group
  shell: "cat /etc/passwd | awk -F: '($3 == 0) { print $1 }'"
  register: cat_5_4_3
  check_mode: no
  changed_when: False
  tags:
    - level-1
    - section-5
    - "5.4.3"
    - scored

- name: 5.4.3 - Ensure default group for the root account is GID 0
  command: usermod -g 0 root
  when: cat_5_4_3.stdout is not defined or cat_5_4_3.stdout != 0
  tags:
    - level-1
    - section-5
    - "5.4.3"
    - scored
