# Standards: 0.11
---

# 5.4.1.1 Ensure password expiration is 90 days or less

- name: 5.4.1.1 - Obtain a list of user accounts
  shell: "egrep ^[^:]+:[^\\!*] /etc/shadow | cut -d: -f1"
  register: egrep_5_4_1_1
  check_mode: no
  changed_when: False
  tags:
    - level-1
    - section-5
    - "5.4.1.1"
    - scored

- name: 5.4.1.1 - Ensure password expiration is 90 days or less
  lineinfile:
    dest: "/etc/login.defs"
    regexp: "^PASS_MAX_DAYS\\s+"
    line: "PASS_MAX_DAYS {{ cis_pass_max_days }}"
  tags:
    - level-1
    - section-5
    - "5.4.1.1"
    - scored

- name: 5.4.1.1 - Set password expiration for all user accounts
  command: "chage --maxdays {{ cis_pass_max_days }} {{ item }}"
  with_items: "{{ egrep_5_4_1_1.stdout_lines }}"
  tags:
    - level-1
    - section-5
    - "5.4.1.1"
    - scored
