---

# 6.1.9 Ensure permissions on /etc/gshadow- are configured

- name: 6.1.9 - Ensure permissions on /etc/gshadow- are configured
  file:
    path: /etc/gshadow-
    owner: root
    group: root
    mode: 0600
  tags:
    - level-1
    - "6.1.9"
    - scored
