# Standards: 0.11
---

# 6.1.5 Ensure permissions on /etc/gshadow are configured

- name: 6.1.5 - Ensure permissions on /etc/gshadow are configured
  file:
    path: /etc/gshadow
    owner: root
    group: root
    mode: 0000
  tags:
    - level-1
    - section-6
    - "6.1.5"
    - scored
