# Standards: 0.11
---

# 6.1.10 Ensure no world writable files exist

- name: 6.1.10 - Audit if any world writable files exist
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -0002
  register: audit_6_1_10
  tags:
    - level-1
    - section-6
    - "6.1.10"
    - scored

- name: 6.1.10 - Ensure no world writable files exist
  fail:
    msg: "{{ audit_6_1_10.stdout_lines }}"
  when:
    - audit_6_1_10.stdout_lines is defined and audit_6_1_10.stdout_lines|length > 0
    - fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - "6.1.10"
    - scored

- name: 6.1.10 - Ensure no world writable files exist
  debug:
    msg: "*** ACTION REQUIRED *** {{ audit_6_1_10.stdout }}"
  when:
    - audit_6_1_10.stdout_lines is defined and audit_6_1_10.stdout_lines|length > 0
    - not fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - "6.1.10"
    - scored
