# Standards: 0.11
---

# 6.1.11 Ensure no unowned files or directories exist

- name: 6.1.11 - Audit if any unowned files or directories exist
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -nouser
  register: audit_6_1_11
  tags:
    - level-1
    - section-6
    - "6.1.11"
    - scored

- name: 6.1.11 - Ensure no unowned files or directories exist
  fail:
    msg: "{{ audit_6_1_11.stdout_lines }}"
  when:
    - audit_6_1_11.stdout_lines is defined and audit_6_1_11.stdout_lines|length > 0
    - fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - "6.1.11"
    - scored

- name: 6.1.11 - Ensure no unowned files or directories exist
  debug:
    msg: "*** ACTION REQUIRED *** {{ audit_6_1_11.stdout }}"
  when:
    - audit_6_1_11.stdout_lines is defined and audit_6_1_11.stdout_lines|length > 0
    - not fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - "6.1.11"
    - scored
