# Standards: 0.11
---

# 6.1.3 Ensure permissions on /etc/shadow are configured

- name: 6.1.3 - Ensure permissions on /etc/shadow are configured
  file:
    path: /etc/shadow
    owner: root
    group: root
    mode: 0000
  tags:
    - level-1
    - section-6
    - "6.1.3"
    - scored
