# Standards: 0.11
---

# 6.2.15 Ensure all groups in /etc/passwd exist in /etc/group

- name: 6.2.15 - Audit existence of groups listed in /etc/passwd against /etc/group
  script: "{{ role_path }}/files/audit_6.2.15.sh"
  check_mode: no
  changed_when: False
  register: audit_6_2_15
  tags:
    - level-1
    - section-6
    - "6.2.15"
    - scored

- name: 6.2.15 - Ensure all groups in /etc/passwd exist in /etc/group
  fail:
    msg: "{{ audit_6_2_15.stdout_lines }}"
  when:
    - audit_6_2_15.stdout_lines is defined and audit_6_2_15.stdout_lines|length > 0
    - fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - "6.2.15"
    - scored

- name: 6.2.15 - Ensure all groups in /etc/passwd exist in /etc/group
  debug:
    msg: "*** ACTION REQUIRED *** {{ audit_6_2_15.stdout }}"
  when:
    - audit_6_2_15.stdout_lines is defined and audit_6_2_15.stdout_lines|length > 0
    - not fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - "6.2.15"
    - scored
