# Standards: 0.11
---

# 6.2.12 Ensure no users have .netrc files

- name: 6.2.12 - Audit users'.netrc files
  script: "{{ role_path }}/files/audit_6.2.12.sh"
  check_mode: no
  changed_when: False
  register: audit_6_2_12
  tags:
    - level-1
    - section-6
    - "6.2.12"
    - scored

- name: 6.2.12 - Ensure no users have .netrc files
  fail:
    msg: "{{ audit_6_2_12.stdout_lines }}"
  when:
    - audit_6_2_12.stdout_lines is defined and audit_6_2_12.stdout_lines|length > 0
    - fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - "6.2.12"
    - scored

- name: 6.2.12 - Ensure no users have .netrc files
  debug:
    msg: "*** ACTION REQUIRED *** {{ audit_6_2_12.stdout }}"
  when:
    - audit_6_2_12.stdout_lines is defined and audit_6_2_12.stdout_lines|length > 0
    - not fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - "6.2.12"
    - scored
