# Standards: 0.11
---

# 6.2.17 Ensure no duplicate GIDs exist

- name: 6.2.17 - Check if duplicate GIDs exist
  script: "{{ role_path }}/files/audit_6.2.17.sh"
  check_mode: no
  changed_when: False
  register: audit_6_2_17
  tags:
    - level-1
    - section-6
    - "6.2.17"
    - scored

- name: 6.2.17 - Ensure no duplicate GIDs exist
  fail:
    msg: "{{ audit_6_2_17.stdout_lines }}"
  when:
    - audit_6_2_17.stdout_lines is defined and audit_6_2_17.stdout_lines|length > 0
    - fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - "6.2.17"
    - scored

- name: 6.2.17 - Ensure no duplicate GIDs exist
  debug:
    msg: "*** ACTION REQUIRED *** {{ audit_6_2_17.stdout }}"
  when:
    - audit_6_2_17.stdout_lines is defined and audit_6_2_17.stdout_lines|length > 0
    - not fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - "6.2.17"
    - scored
