# Standards: 0.11
---

# 6.2.11 Ensure no users have .forward files

- name: 6.2.11 - Audit users' forward files
  script: "{{ role_path }}/files/audit_6.2.11.sh"
  check_mode: no
  changed_when: False
  register: audit_6_2_11
  tags:
    - level-1
    - section-6
    - "6.2.11"
    - scored

- name: 6.2.11 - Ensure no users have .forward files
  fail:
    msg: "{{ audit_6_2_11.stdout }}"
  when:
    - audit_6_2_11.stdout_lines is defined and audit_6_2_11.stdout_lines|length > 0
    - fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - "6.2.11"
    - scored

- name: 6.2.11 - Ensure no users have .forward files
  debug:
    msg: "*** ACTION REQUIRED *** {{ audit_6_2_11.stdout }}"
  when:
    - audit_6_2_11.stdout_lines is defined and audit_6_2_11.stdout_lines|length > 0
    - not fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - "6.2.11"
    - scored
