---

# 6.2.10 Ensure users' dot files are not group or world writable

- name: 6.2.10 - Audit users' dot files permissions
  script: "{{ role_path }}/files/audit_6.2.10.sh"
  register: audit_6_2_10
  tags:
    - level-1
    - "6.2.10"
    - scored

- name: 6.2.10 - Ensure users' dot files are not group or world writable
  fail:
    msg: "{{ audit_6_2_10.stdout_lines }}"
  when: audit_6_2_10.stdout_lines is defined and audit_6_2_10.stdout_lines|length > 0
  tags:
    - level-1
    - "6.2.10"
    - scored
