# Standards: 0.11
---

# 6.2.16 Ensure no duplicate UIDs exist

- name: 6.2.16 - Check if duplicate UIDs exist
  script: "{{ role_path }}/files/audit_6.2.16.sh"
  check_mode: no
  changed_when: False
  register: audit_6_2_16
  tags:
    - level-1
    - section-6
    - "6.2.16"
    - scored

- name: 6.2.16 - Ensure no duplicate UIDs exist
  fail:
    msg: "{{ audit_6_2_16.stdout_lines }}"
  when:
    - audit_6_2_16.stdout_lines is defined and audit_6_2_16.stdout_lines|length > 0
    - fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - "6.2.16"
    - scored

- name: 6.2.16 - Ensure no duplicate UIDs exist
  debug:
    msg: "*** ACTION REQUIRED *** {{ audit_6_2_16.stdout }}"
  when:
    - audit_6_2_16.stdout_lines is defined and audit_6_2_16.stdout_lines|length > 0
    - not fail_on_manual_remediation_actions
  tags:
    - level-1
    - section-6
    - "6.2.16"
    - scored
